"""Immutable source-asset persistence (Stage 3d neutral home; introduced 3c doc 04 §9.1).

Thin helpers over the standalone ``source_asset`` table (raw uploaded TXT/CSV bytes
evidence). The table is domain-neutral: it predates any work object root and is
shared by every external work object that ingests a source file (Trading Signal 3c,
Trade Log 3d, and later slices). These helpers add rows and NEVER commit (the
caller's tx owns the commit).

``repositories/trading_signal.py`` re-exports these for back-compat so no 3c caller
changes.
"""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from entropia.infrastructure.postgres.models import SourceAsset


async def create_source_asset(
    session: AsyncSession,
    *,
    source_asset_id: str,
    owner_principal_id: str | None,
    object_key: str,
    raw_asset_hash: str,
    size_bytes: int,
    content_type: str | None,
    original_filename: str | None,
    draft_id: str | None,
    uploaded_by_principal_id: str | None,
) -> SourceAsset:
    """Insert an immutable raw source-asset row (``source_asset_id`` pre-generated by
    the caller so it can key the object-storage upload). No commit.

    Flushes before returning so the PK is present for any FK child created in the
    same unit of work — SQLAlchemy does NOT derive parent-before-child INSERT order
    from a bare ``ForeignKey`` (L1). In the normal flow the asset is created and
    committed in the upload tx, and the record batch is created in the later worker
    tx; this flush also makes a same-tx caller safe.
    """
    asset = SourceAsset(
        source_asset_id=source_asset_id,
        owner_principal_id=owner_principal_id,
        draft_id=draft_id,
        object_key=object_key,
        raw_asset_hash=raw_asset_hash,
        size_bytes=size_bytes,
        content_type=content_type,
        original_filename=original_filename,
        uploaded_by_principal_id=uploaded_by_principal_id,
    )
    session.add(asset)
    await session.flush()
    return asset


async def get_source_asset(session: AsyncSession, source_asset_id: str) -> SourceAsset | None:
    return await session.get(SourceAsset, source_asset_id)


async def find_source_asset_by_hash(
    session: AsyncSession, *, owner_principal_id: str | None, raw_asset_hash: str
) -> SourceAsset | None:
    """Return an existing identical upload by the same owner (content dedup)."""
    stmt = (
        select(SourceAsset)
        .where(
            SourceAsset.owner_principal_id == owner_principal_id,
            SourceAsset.raw_asset_hash == raw_asset_hash,
        )
        .order_by(SourceAsset.source_asset_id)
        .limit(1)
    )
    return (await session.execute(stmt)).scalars().first()


__all__ = ["create_source_asset", "find_source_asset_by_hash", "get_source_asset"]
