"""Trading Signal support-table persistence (Stage 3c, doc 04 §9.1).

Thin helpers over ``source_asset`` and ``normalized_signal_event_revision``. Both
are standalone tables (no ``entity_registry`` anchor); the Trading Signal
root/revision reuse the 3a Mainboard work-object repo. These helpers add rows and
NEVER commit (the caller's tx owns the commit).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from entropia.domain.trading_signal.enums import NormalizedRevisionStatus
from entropia.infrastructure.postgres.models import (
    NormalizedSignalEventRevision,
    SourceAsset,
)
from entropia.shared.ids import new_id


async def create_source_asset(
    session: AsyncSession,
    *,
    source_asset_id: str,
    owner_principal_id: str | None,
    object_key: str,
    raw_asset_hash: str,
    size_bytes: int,
    content_type: str | None,
    original_filename: str | None,
    draft_id: str | None,
    uploaded_by_principal_id: str | None,
) -> SourceAsset:
    """Insert an immutable raw source-asset row (``source_asset_id`` pre-generated by
    the caller so it can key the object-storage upload). No commit.

    Flushes before returning so the PK is present for any FK child created in the
    same unit of work — SQLAlchemy does NOT derive parent-before-child INSERT order
    from a bare ``ForeignKey`` (L1). In the normal flow the asset is created and
    committed in the upload tx, and ``create_normalized_revision`` runs in the later
    worker tx; this flush also makes a same-tx caller safe.
    """
    asset = SourceAsset(
        source_asset_id=source_asset_id,
        owner_principal_id=owner_principal_id,
        draft_id=draft_id,
        object_key=object_key,
        raw_asset_hash=raw_asset_hash,
        size_bytes=size_bytes,
        content_type=content_type,
        original_filename=original_filename,
        uploaded_by_principal_id=uploaded_by_principal_id,
    )
    session.add(asset)
    await session.flush()
    return asset


async def get_source_asset(session: AsyncSession, source_asset_id: str) -> SourceAsset | None:
    return await session.get(SourceAsset, source_asset_id)


async def find_source_asset_by_hash(
    session: AsyncSession, *, owner_principal_id: str | None, raw_asset_hash: str
) -> SourceAsset | None:
    """Return an existing identical upload by the same owner (content dedup, doc 04 §3.1)."""
    stmt = (
        select(SourceAsset)
        .where(
            SourceAsset.owner_principal_id == owner_principal_id,
            SourceAsset.raw_asset_hash == raw_asset_hash,
        )
        .order_by(SourceAsset.source_asset_id)
        .limit(1)
    )
    return (await session.execute(stmt)).scalars().first()


async def create_normalized_revision(
    session: AsyncSession,
    *,
    source_asset_id: str,
    job_id: str | None,
    status: NormalizedRevisionStatus,
    instrument_id: str | None,
    accepted_count: int,
    skipped_count: int,
    events: list[dict[str, Any]],
    skipped_rows: list[dict[str, Any]],
    validation_summary: dict[str, Any] | None,
    earliest_available_time: datetime | None,
    content_hash: str,
    created_by_principal_id: str | None,
) -> NormalizedSignalEventRevision:
    """Insert an immutable normalized signal-event revision. No commit.

    ``source_asset`` must already exist (created + committed by the upload command
    that ran before this import), so the FK is satisfiable at flush time.
    """
    revision = NormalizedSignalEventRevision(
        normalized_revision_id=new_id("normsig"),
        source_asset_id=source_asset_id,
        job_id=job_id,
        status=status,
        instrument_id=instrument_id,
        accepted_count=accepted_count,
        skipped_count=skipped_count,
        events=events,
        skipped_rows=skipped_rows,
        validation_summary=validation_summary,
        earliest_available_time=earliest_available_time,
        content_hash=content_hash,
        work_object_revision_id=None,
        created_by_principal_id=created_by_principal_id,
    )
    session.add(revision)
    return revision


async def get_normalized_revision(
    session: AsyncSession, normalized_revision_id: str
) -> NormalizedSignalEventRevision | None:
    return await session.get(NormalizedSignalEventRevision, normalized_revision_id)


async def get_normalized_revision_for_job(
    session: AsyncSession, job_id: str
) -> NormalizedSignalEventRevision | None:
    stmt = (
        select(NormalizedSignalEventRevision)
        .where(NormalizedSignalEventRevision.job_id == job_id)
        .order_by(NormalizedSignalEventRevision.normalized_revision_id)
        .limit(1)
    )
    return (await session.execute(stmt)).scalars().first()


def link_normalized_to_revision(
    normalized: NormalizedSignalEventRevision, work_object_revision_id: str
) -> None:
    """Pin a normalized revision to the Trading Signal work-object revision it backs."""
    normalized.work_object_revision_id = work_object_revision_id


__all__ = [
    "create_normalized_revision",
    "create_source_asset",
    "find_source_asset_by_hash",
    "get_normalized_revision",
    "get_normalized_revision_for_job",
    "get_source_asset",
    "link_normalized_to_revision",
]
